python3 videoEstimatorNoYOLO.py --video 1 --metric iou > logs/video1.txt
python3 videoEstimatorNoYOLO.py --video 2 --metric iou > logs/video2.txt
python3 videoEstimatorNoYOLO.py --video 5 --metric iou > logs/video5.txt
python3 videoEstimatorNoYOLO.py --video 6 --metric iou > logs/video6.txt
python3 videoEstimatorNoYOLO.py --video 7 --metric iou > logs/video7.txt
python3 videoEstimatorNoYOLO.py --video 9 --metric iou > logs/video9.txt
python3 videoEstimatorNoYOLO.py --video 11 --metric iou > logs/video11.txt
python3 videoEstimatorNoYOLO.py --video 12 --metric iou > logs/video12.txt
python3 videoEstimatorNoYOLO.py --video 13 --metric iou > logs/video13.txt
python3 videoEstimatorNoYOLO.py --video 14 --metric iou > logs/video14.txt