python3 detectionCapture.py --video 1
python3 detectionCapture.py --video 2
python3 detectionCapture.py --video 5
python3 detectionCapture.py --video 6
python3 detectionCapture.py --video 7
python3 detectionCapture.py --video 9
python3 detectionCapture.py --video 10
python3 detectionCapture.py --video 11
python3 detectionCapture.py --video 12
python3 detectionCapture.py --video 13
python3 detectionCapture.py --video 14
